// 回测的时候可能交易所服务器处于关闭状态, 此时是不能通过ctp接口查询到Exchange和Product信息的, 此时就需要用到此模块中的数据

var localProduct = 
{ ag: 
   { ProductID: 'ag',
     ProductName: '白银',
     ExchangeID: 'SHFE',
     ProductClass: '1',
     VolumeMultiple: 15,
     PriceTick: 1,
     MaxMarketOrderVolume: 500,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 500,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '1',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '上海期货交易所' },
  sn: 
   { ProductID: 'sn',
     ProductName: '锡',
     ExchangeID: 'SHFE',
     ProductClass: '1',
     VolumeMultiple: 1,
     PriceTick: 10,
     MaxMarketOrderVolume: 500,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 500,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '1',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1,
     ExchangeName: '上海期货交易所' },
  zn: 
   { ProductID: 'zn',
     ProductName: '锌',
     ExchangeID: 'SHFE',
     ProductClass: '1',
     VolumeMultiple: 5,
     PriceTick: 5,
     MaxMarketOrderVolume: 500,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 500,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '1',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '上海期货交易所' },
  IH: 
   { ProductID: 'IH',
     ProductName: '上证50指数',
     ExchangeID: 'CFFEX',
     ProductClass: '1',
     VolumeMultiple: 300,
     PriceTick: 0.2,
     MaxMarketOrderVolume: 50,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 100,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1,
     ExchangeName: '中国金融交易所' },
  TA: 
   { ProductID: 'TA',
     ProductName: '精对苯二甲酸',
     ExchangeID: 'CZCE',
     ProductClass: '1',
     VolumeMultiple: 5,
     PriceTick: 2,
     MaxMarketOrderVolume: 200,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 1000,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '1',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '郑州商品交易所' },
  SR: 
   { ProductID: 'SR',
     ProductName: '白砂糖',
     ExchangeID: 'CZCE',
     ProductClass: '1',
     VolumeMultiple: 10,
     PriceTick: 1,
     MaxMarketOrderVolume: 200,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 1000,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '1',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '郑州商品交易所' },
  LR: 
   { ProductID: 'LR',
     ProductName: '晚籼稻',
     ExchangeID: 'CZCE',
     ProductClass: '1',
     VolumeMultiple: 20,
     PriceTick: 1,
     MaxMarketOrderVolume: 200,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 1000,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '1',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '郑州商品交易所' },
  ru: 
   { ProductID: 'ru',
     ProductName: '天然橡胶',
     ExchangeID: 'SHFE',
     ProductClass: '1',
     VolumeMultiple: 10,
     PriceTick: 5,
     MaxMarketOrderVolume: 500,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 500,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '1',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '上海期货交易所' },
  IC: 
   { ProductID: 'IC',
     ProductName: '中证500指数',
     ExchangeID: 'CFFEX',
     ProductClass: '1',
     VolumeMultiple: 200,
     PriceTick: 0.2,
     MaxMarketOrderVolume: 50,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 100,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1,
     ExchangeName: '中国金融交易所' },
  IF: 
   { ProductID: 'IF',
     ProductName: '沪深300指数',
     ExchangeID: 'CFFEX',
     ProductClass: '1',
     VolumeMultiple: 300,
     PriceTick: 0.2,
     MaxMarketOrderVolume: 50,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 100,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '中国金融交易所' },
  RM: 
   { ProductID: 'RM',
     ProductName: '菜籽粕',
     ExchangeID: 'CZCE',
     ProductClass: '1',
     VolumeMultiple: 10,
     PriceTick: 1,
     MaxMarketOrderVolume: 200,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 1000,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '1',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '郑州商品交易所' },
  ME: 
   { ProductID: 'ME',
     ProductName: '甲醇',
     ExchangeID: 'CZCE',
     ProductClass: '1',
     VolumeMultiple: 50,
     PriceTick: 1,
     MaxMarketOrderVolume: 200,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 1000,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '1',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '郑州商品交易所' },
  TF: 
   { ProductID: 'TF',
     ProductName: '5年期国债',
     ExchangeID: 'CFFEX',
     ProductClass: '1',
     VolumeMultiple: 10000,
     PriceTick: 0.005,
     MaxMarketOrderVolume: 50,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 200,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1,
     ExchangeName: '中国金融交易所' },
  TC: 
   { ProductID: 'TC',
     ProductName: '动力煤',
     ExchangeID: 'CZCE',
     ProductClass: '1',
     VolumeMultiple: 200,
     PriceTick: 0.2,
     MaxMarketOrderVolume: 200,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 1000,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '1',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '郑州商品交易所' },
  hc: 
   { ProductID: 'hc',
     ProductName: '热轧卷板',
     ExchangeID: 'SHFE',
     ProductClass: '1',
     VolumeMultiple: 10,
     PriceTick: 1,
     MaxMarketOrderVolume: 500,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 500,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '1',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1,
     ExchangeName: '上海期货交易所' },
  ni: 
   { ProductID: 'ni',
     ProductName: '镍',
     ExchangeID: 'SHFE',
     ProductClass: '1',
     VolumeMultiple: 1,
     PriceTick: 10,
     MaxMarketOrderVolume: 500,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 500,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '1',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1,
     ExchangeName: '上海期货交易所' },
  pb: 
   { ProductID: 'pb',
     ProductName: '铅',
     ExchangeID: 'SHFE',
     ProductClass: '1',
     VolumeMultiple: 5,
     PriceTick: 5,
     MaxMarketOrderVolume: 500,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 500,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '1',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '上海期货交易所' },
  j: 
   { ProductID: 'j',
     ProductName: '冶金焦炭',
     ExchangeID: 'DCE',
     ProductClass: '1',
     VolumeMultiple: 100,
     PriceTick: 0.5,
     MaxMarketOrderVolume: 500,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 500,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1,
     ExchangeName: '大连商品交易所' },
  SRC: 
   { ProductID: 'SRC',
     ProductName: '白糖看涨期权',
     ExchangeID: 'CZCE',
     ProductClass: '2',
     VolumeMultiple: 10,
     PriceTick: 0.5,
     MaxMarketOrderVolume: 100,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 100,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '1',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1,
     ExchangeName: '郑州商品交易所' },
  bu: 
   { ProductID: 'bu',
     ProductName: '石油沥青',
     ExchangeID: 'SHFE',
     ProductClass: '1',
     VolumeMultiple: 10,
     PriceTick: 2,
     MaxMarketOrderVolume: 500,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 500,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '1',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '上海期货交易所' },
  RS: 
   { ProductID: 'RS',
     ProductName: '油菜籽',
     ExchangeID: 'CZCE',
     ProductClass: '1',
     VolumeMultiple: 10,
     PriceTick: 1,
     MaxMarketOrderVolume: 200,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 1000,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '1',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '郑州商品交易所' },
  WH: 
   { ProductID: 'WH',
     ProductName: '优质强筋小麦',
     ExchangeID: 'CZCE',
     ProductClass: '1',
     VolumeMultiple: 20,
     PriceTick: 1,
     MaxMarketOrderVolume: 200,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 1000,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '1',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '郑州商品交易所' },
  jm: 
   { ProductID: 'jm',
     ProductName: '焦煤',
     ExchangeID: 'DCE',
     ProductClass: '1',
     VolumeMultiple: 60,
     PriceTick: 0.5,
     MaxMarketOrderVolume: 1000,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 1000,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1,
     ExchangeName: '大连商品交易所' },
  m_o: 
   { ProductID: 'm_o',
     ProductName: '豆粕期权',
     ExchangeID: 'DCE',
     ProductClass: '2',
     VolumeMultiple: 10,
     PriceTick: 0.5,
     MaxMarketOrderVolume: 100,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 100,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1,
     ExchangeName: '大连商品交易所' },
  a: 
   { ProductID: 'a',
     ProductName: '黄大豆1号',
     ExchangeID: 'DCE',
     ProductClass: '1',
     VolumeMultiple: 10,
     PriceTick: 1,
     MaxMarketOrderVolume: 1000,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 1000,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '大连商品交易所' },
  au: 
   { ProductID: 'au',
     ProductName: '黄金',
     ExchangeID: 'SHFE',
     ProductClass: '1',
     VolumeMultiple: 1000,
     PriceTick: 0.05,
     MaxMarketOrderVolume: 500,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 500,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '1',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '上海期货交易所' },
  wr: 
   { ProductID: 'wr',
     ProductName: '线材',
     ExchangeID: 'SHFE',
     ProductClass: '1',
     VolumeMultiple: 10,
     PriceTick: 1,
     MaxMarketOrderVolume: 500,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 500,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '1',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '上海期货交易所' },
  i: 
   { ProductID: 'i',
     ProductName: '铁矿石',
     ExchangeID: 'DCE',
     ProductClass: '1',
     VolumeMultiple: 100,
     PriceTick: 0.5,
     MaxMarketOrderVolume: 1000,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 1000,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1,
     ExchangeName: '大连商品交易所' },
  pp: 
   { ProductID: 'pp',
     ProductName: '聚丙烯',
     ExchangeID: 'DCE',
     ProductClass: '1',
     VolumeMultiple: 5,
     PriceTick: 1,
     MaxMarketOrderVolume: 1000,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 1000,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '大连商品交易所' },
  b: 
   { ProductID: 'b',
     ProductName: '黄大豆2号',
     ExchangeID: 'DCE',
     ProductClass: '1',
     VolumeMultiple: 10,
     PriceTick: 1,
     MaxMarketOrderVolume: 1000,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 1000,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '大连商品交易所' },
  l: 
   { ProductID: 'l',
     ProductName: '线型低密度聚乙烯',
     ExchangeID: 'DCE',
     ProductClass: '1',
     VolumeMultiple: 5,
     PriceTick: 5,
     MaxMarketOrderVolume: 1000,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 1000,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '大连商品交易所' },
  al: 
   { ProductID: 'al',
     ProductName: '铝',
     ExchangeID: 'SHFE',
     ProductClass: '1',
     VolumeMultiple: 5,
     PriceTick: 5,
     MaxMarketOrderVolume: 500,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 500,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '1',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '上海期货交易所' },
  cu: 
   { ProductID: 'cu',
     ProductName: '铜',
     ExchangeID: 'SHFE',
     ProductClass: '1',
     VolumeMultiple: 5,
     PriceTick: 10,
     MaxMarketOrderVolume: 500,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 500,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '1',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '上海期货交易所' },
  fu: 
   { ProductID: 'fu',
     ProductName: '燃料油',
     ExchangeID: 'SHFE',
     ProductClass: '1',
     VolumeMultiple: 50,
     PriceTick: 1,
     MaxMarketOrderVolume: 500,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 500,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '1',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '上海期货交易所' },
  rb: 
   { ProductID: 'rb',
     ProductName: '螺纹钢',
     ExchangeID: 'SHFE',
     ProductClass: '1',
     VolumeMultiple: 10,
     PriceTick: 1,
     MaxMarketOrderVolume: 500,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 500,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '1',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '上海期货交易所' },
  OI: 
   { ProductID: 'OI',
     ProductName: '菜籽油',
     ExchangeID: 'CZCE',
     ProductClass: '1',
     VolumeMultiple: 10,
     PriceTick: 2,
     MaxMarketOrderVolume: 200,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 1000,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '1',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '郑州商品交易所' },
  RI: 
   { ProductID: 'RI',
     ProductName: '早籼稻',
     ExchangeID: 'CZCE',
     ProductClass: '1',
     VolumeMultiple: 20,
     PriceTick: 1,
     MaxMarketOrderVolume: 200,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 1000,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '1',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '郑州商品交易所' },
  FG: 
   { ProductID: 'FG',
     ProductName: '玻璃',
     ExchangeID: 'CZCE',
     ProductClass: '1',
     VolumeMultiple: 20,
     PriceTick: 1,
     MaxMarketOrderVolume: 200,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 1000,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '1',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '郑州商品交易所' },
  fb: 
   { ProductID: 'fb',
     ProductName: '中密度纤维板',
     ExchangeID: 'DCE',
     ProductClass: '1',
     VolumeMultiple: 500,
     PriceTick: 0.05,
     MaxMarketOrderVolume: 1000,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 1000,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '大连商品交易所' },
  T: 
   { ProductID: 'T',
     ProductName: '10年期国债',
     ExchangeID: 'CFFEX',
     ProductClass: '1',
     VolumeMultiple: 10000,
     PriceTick: 0.005,
     MaxMarketOrderVolume: 50,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 200,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1,
     ExchangeName: '中国金融交易所' },
  jd: 
   { ProductID: 'jd',
     ProductName: '鲜鸡蛋',
     ExchangeID: 'DCE',
     ProductClass: '1',
     VolumeMultiple: 10,
     PriceTick: 1,
     MaxMarketOrderVolume: 300,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 300,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '大连商品交易所' },
  m: 
   { ProductID: 'm',
     ProductName: '豆粕',
     ExchangeID: 'DCE',
     ProductClass: '1',
     VolumeMultiple: 10,
     PriceTick: 1,
     MaxMarketOrderVolume: 1000,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 1000,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '大连商品交易所' },
  p: 
   { ProductID: 'p',
     ProductName: '棕榈油',
     ExchangeID: 'DCE',
     ProductClass: '1',
     VolumeMultiple: 10,
     PriceTick: 2,
     MaxMarketOrderVolume: 1000,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 1000,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '大连商品交易所' },
  SM: 
   { ProductID: 'SM',
     ProductName: '锰硅',
     ExchangeID: 'CZCE',
     ProductClass: '1',
     VolumeMultiple: 5,
     PriceTick: 2,
     MaxMarketOrderVolume: 200,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 1000,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '1',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '郑州商品交易所' },
  v: 
   { ProductID: 'v',
     ProductName: '聚氯乙烯',
     ExchangeID: 'DCE',
     ProductClass: '1',
     VolumeMultiple: 5,
     PriceTick: 5,
     MaxMarketOrderVolume: 1000,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 1000,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '大连商品交易所' },
  JR: 
   { ProductID: 'JR',
     ProductName: '粳稻谷',
     ExchangeID: 'CZCE',
     ProductClass: '1',
     VolumeMultiple: 20,
     PriceTick: 1,
     MaxMarketOrderVolume: 200,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 1000,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '1',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '郑州商品交易所' },
  PM: 
   { ProductID: 'PM',
     ProductName: '普通小麦',
     ExchangeID: 'CZCE',
     ProductClass: '1',
     VolumeMultiple: 50,
     PriceTick: 1,
     MaxMarketOrderVolume: 200,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 1000,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '1',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '郑州商品交易所' },
  bb: 
   { ProductID: 'bb',
     ProductName: '细木工板',
     ExchangeID: 'DCE',
     ProductClass: '1',
     VolumeMultiple: 500,
     PriceTick: 0.05,
     MaxMarketOrderVolume: 1000,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 1000,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '大连商品交易所' },
  cs: 
   { ProductID: 'cs',
     ProductName: '玉米淀粉',
     ExchangeID: 'DCE',
     ProductClass: '1',
     VolumeMultiple: 10,
     PriceTick: 1,
     MaxMarketOrderVolume: 1000,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 1000,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '大连商品交易所' },
  y: 
   { ProductID: 'y',
     ProductName: '豆油',
     ExchangeID: 'DCE',
     ProductClass: '1',
     VolumeMultiple: 10,
     PriceTick: 2,
     MaxMarketOrderVolume: 1000,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 1000,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '大连商品交易所' },
  c: 
   { ProductID: 'c',
     ProductName: '黄玉米',
     ExchangeID: 'DCE',
     ProductClass: '1',
     VolumeMultiple: 10,
     PriceTick: 1,
     MaxMarketOrderVolume: 2000,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 2000,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '0',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '大连商品交易所' },
  SF: 
   { ProductID: 'SF',
     ProductName: '硅铁',
     ExchangeID: 'CZCE',
     ProductClass: '1',
     VolumeMultiple: 5,
     PriceTick: 2,
     MaxMarketOrderVolume: 200,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 1000,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '1',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '郑州商品交易所' },
  CF: 
   { ProductID: 'CF',
     ProductName: '一号棉花',
     ExchangeID: 'CZCE',
     ProductClass: '1',
     VolumeMultiple: 5,
     PriceTick: 5,
     MaxMarketOrderVolume: 200,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 1000,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '1',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '郑州商品交易所' },
  ZC: 
   { ProductID: 'ZC',
     ProductName: '动力煤',
     ExchangeID: 'CZCE',
     ProductClass: '1',
     VolumeMultiple: 100,
     PriceTick: 0.2,
     MaxMarketOrderVolume: 200,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 1000,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '1',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1,
     ExchangeName: '郑州商品交易所' },
  SRP: 
   { ProductID: 'SRP',
     ProductName: '白糖看跌期权',
     ExchangeID: 'CZCE',
     ProductClass: '2',
     VolumeMultiple: 10,
     PriceTick: 0.5,
     MaxMarketOrderVolume: 100,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 100,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '1',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1,
     ExchangeName: '郑州商品交易所' },
  MA: 
   { ProductID: 'MA',
     ProductName: '甲醇',
     ExchangeID: 'CZCE',
     ProductClass: '1',
     VolumeMultiple: 10,
     PriceTick: 1,
     MaxMarketOrderVolume: 200,
     MinMarketOrderVolume: 1,
     MaxLimitOrderVolume: 1000,
     MinLimitOrderVolume: 1,
     PositionType: '2',
     PositionDateType: '2',
     CloseDealType: '1',
     TradeCurrencyID: 'CNY',
     MortgageFundUseRange: '0',
     ExchangeProductID: '',
     UnderlyingMultiple: 1.7976931348623157e+308,
     ExchangeName: '郑州商品交易所' }
};

module.exports = localProduct;